name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    permissions:
      contents: read
    uses: modeled-information-format/.github/.github/workflows/reusable-actionlint.yml@63bbc0352a07d949c0d4c040e88bea39b5991ce7
